# Generated by Django 5.2.17 on 2026-08-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='grade_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Например, для '7B' указать 7. Нужно для проверки норм СанПиН РК (приказ МЗ РК № ҚР ДСМ-76) — например, запрет сдвоенных уроков в начальной школе (1-4 классы). Если не указать — эти проверки для класса просто не будут выполняться.", null=True, verbose_name='Параллель (класс), 1-12'),
        ),
        migrations.AddField(
            model_name='subject',
            name='difficulty_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 — самый лёгкий предмет (физкультура, музыка, труд), 5 — самый сложный (математика, языки, физика). Основано на шкале трудности предметов из Приложения 4 к приказу МЗ РК № ҚР ДСМ-76. Используется, чтобы предупреждать, если сложный предмет стоит первым/последним уроком или таких предметов слишком много в один день. Можно не указывать — тогда проверка для предмета не работает.', null=True, verbose_name='Балл трудности (СанПиН РК), 1-5'),
        ),
    ]
